### ISSUE TITLE
Won't catch pokemon

### ISSUE THREAD

**Issue by SSinischo** [SwipeX/PokeMate#36]
Hi.  The bot seems to catch all the pokemon around when first started up, but then doesn't find a single one as it traverses its path.  Also, tagging pokestops are not awarding XP.  I am not softbanned.

**Comment by MDashK** [comment]
The XP issue is solved in the latest commit, but it hasn't been released in JAR format yet.
About the Pokemon: Let it run for quite a while, and it will eventually capture more pokemon. Sometimes the area is not that populated...

**Comment by SwipeX** [comment]
To add, I need to finish up the UI before I can release this. I should have set up a dev branch but ill deal with that later.

**Comment by SwipeX** [comment]
Please report back on lastest release when you can @SSinischo

**Comment by SSinischo** [comment]
Using latest release (with "gradlew run"... not sure how else to compile it using gradlew.  Using "gradlew jar" made a corrupt jarfile)

Anyway, the pokestop/XP bug is fixed, but it still won't catch any Pokemon aside from the inital handful when it is started up.  My speed is set to 5m/s and all that's showing in the console are perpetual "profile updates" with an occasional interruption by the walker.  No Pokestops are being tagged.

**Comment by SSinischo** [comment]
I should add that I'm running the bot at the New York City Town Hall, so it shouldn't have any issues finding pokemon in the area.  

A slightly off-topic suggestion:  why don't you make the bot traverse to near pokestops as they are discovered instead of a static predefined path using Google Directions API?  It seems like a lot of the pokemon/pokestops are off the road it is traveling on

**Comment by SwipeX** [comment]
5 m/s might be fast. I personally run at 1 m/s for testing. 
To add: Almost all pokestops are along roads/sidewalks/dirt paths. The directions API will use all of these mediums and should come across a decent amount of pokestops. We do have plans to try to get it to be more 'pokestop' oriented. However it should tag enough to give you pokeballs.

**Comment by SSinischo** [comment]
Switched to 1m/s and still catching/tagging like once every five minutes after a 30 minute test run.

**Comment by SippieCup** [comment]
This is actually due to server communication issues and has been fixed in the recent commits. Closing thread. Please open a new issue if this continues.
